config/routes.rb
YellowRed::Application.routes.draw do

  root :to => 'static_pages#home'
  get 'lobby', :to => 'sessions#lobby'
  get 'signup', :to => 'users#new'
  
  resource :session, :only => [:create, :destroy]
  
  resources :users, :only => [:create]
  resource :profile, :only => [:show, :edit, :update]
  
  resource :saved_search, :only => [:show, :update]
  get 'saved_search/results', :to => 'saved_searches#results'
  
  resources :messages, :only => [:index, :show, :create, :destroy]
  
  resources :maybes, :only => [:create, :update]
  delete 'maybes/:profile_id' => 'maybes#destroy'
  get 'my-maybe-list', :to => 'maybes#maybe_list'
  get 'my-nope-list', :to => 'maybes#nope_list'
  
  resources :stars, :only => [:index, :create]
  delete 'stars/:profile_id' => 'stars#destroy'
  get 'who-i-starred', :to => 'stars#index'
  get 'who-starred-me', :to => 'stars#starred_me'
  
  resources :profiles, :only => [:index, :show]
  get 'check-username/:username', :to => 'profiles#taken'
  get 'dev', :to => 'profiles#clausti'
  get ':username', :to => 'profiles#show'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home 
    @user = current_user
    @search = current_user.saved_search
    @profile = Profile.new
    
    render :home
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div id="all-content">
	
	<div id="left-sidebar" class="round-corners shadow">
    <a href="/#clausti">Hire the Dev</a> <hr>
		<a href="/">Home/Search</a> <hr>
		<a href="#/profiles">Browse Profiles</a> <hr>
		<a href="#/profile">My Profile</a> <hr>
		<a href="#/messages">Messages</a> <hr>
		<a href="#/my-maybe-list">Maybes?</a> <hr>
		<a href="#/my-nope-list">Nopes!</a> <hr>
		<a href="#/who-i-starred">Who I starred</a> <hr>
		<a href="#/who-starred-me">Who starred me</a>
	</div>
	
	<div id="central-content" class="round-corners">
		<div id="search-box" class="round-corners shadow">
			<%= render "shared/errors_marquee" %>
	
			<form action="<%= saved_search_url %>" method="post" id="search-form" accept-charset="utf-8">
				<input type="hidden" name="_method" value="PUT">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
			<div id="search-form-seeking">
				<div class="checkbox-group">
					Looking for:<br>
						<div class="checkbox-group">
							<input type="checkbox" 
										 name="search[friends_wanted]" 
										 value="true"
										 <% if @search.friends_wanted %>
											 checked
										 <% end %>> Friends<br>
							<input type="checkbox" 
										 name="search[dating_wanted]" 
										 value="true"
										 <% if @search.dating_wanted %>
											 checked
										 <% end %>> Dating<br>
							<input type="checkbox" 
										 name="search[hookups_wanted]" 
										 value="true"
										 <% if @search.hookups_wanted %>
											 checked
										 <% end %>> Hookups<br>
						</div>
				</div>
				
				<div class="checkbox-group">
					Interested in:<br>
						<div class="checkbox-group">
							<input type="checkbox" 
										 name="search[men_wanted]" 
										 value="true"
										 <% if @search.men_wanted %>
											 checked
										 <% end %>> Men<br>
							<input type="checkbox" 
										 name="search[women_wanted]" 
										 value="true"
										 <% if @search.women_wanted %>
											 checked
										 <% end %>> Women<br>
							<input type="checkbox" 
										 name="search[nonbinary_wanted]" 
										 value="true"
										 <% if @search.nonbinary_wanted %>
											 checked
										 <% end %>> Genderqueer/Nonbinary<br>	
						</div>
				</div>
			</div>
	
			<div id="their-stats">
				<label for="search_height">Height</label>
				<select name="search[height]" id="search_height">
					<option value=""></option>
					<% options = Profile::HEIGHTS %>
					<% options.each do |height| %>
				    <option value="<%= height %> %>"
							<% if @search.height == height %>
									selected
							<% end %>><%= Profile.height_string(height) %></option>
					<% end %>	
				</select><br>		
		
				<label for="search_body_type">Body Type</label>
				<select name="search[body_type]" id="search_body_type">
					<option value=""></option>
					<% options = Profile::BODY_TYPES %>
					<% options.each do |body_type| %>
				    <option value="<%= body_type %>"
							<% if @search.body_type == body_type %>
								selected
						  <% end %>><%= body_type %></option>
					<% end %>				
				</select><br>

				<label for="search_religion">Religion</label>
				<select name="search[religion]" id="search_religion">
					<option value=""></option>
					<% options = Profile::RELIGIONS %>
					<% options.each do |religion| %>
				    <option value="<%= religion %>"
							<% if @search.religion == religion %>
								selected
						  <% end %>><%= religion %></option>
					<% end %>				
				</select><br>
		
				<label for="search_education">Education</label>
				<select name="search[education]" id="search_education">
					<option value=""></option>
					<% options = Profile::EDUCATION_LEVELS %>
					<% options.each do |education| %>
				    <option value="<%= education %>"
							<% if @search.education == education %>
								selected
						  <% end %>><%= education %></option>
					<% end %>					
				</select><br>
		
				<label for="search_children">Kids?</label>
				<select name="search[children]" id="search_children">
					<option value=""></option>
					<% options = Profile::CHILDREN_CHOICES %>
					<% options.each do |children| %>
				    <option value="<%= children %>"
							<% if @search.children == children %>
								selected
						  <% end %>><%= children %></option>
					<% end %>				
				</select><br>
		
				<label for="search_pets">Pets?</label>
				<select name="search[pets]" id="search_pets">
					<option value=""></option>
					<% options = Profile::PET_CHOICES %>
					<% options.each do |pets| %>
				    <option value="<%= pets %>"
							<% if @search.pets == pets %>
								selected
						  <% end %>><%= pets %></option>
					<% end %>				
				</select>
				<br>
				<br>
				<div style="float:right;padding-right:10px">
					<input class="button" type="submit" value="Search" id="search-submit">
				</div>
			</div>

			</form>
		</div>
		
		<div id="search-results">
		</div>
	</div>
	
	<div id="right-sidebar">
		<div id="yellow-box" class="round-corners shadow">
      <div id="inner-yellow">
        <div id="inner-yellow-words" class="round-corners">
          Drop Maybes Here
        </div>
        <div id="inner-yellow-cards">
          
        </div>
      </div>
		</div>
		
		<div id="red-box" class="round-corners shadow">
      <div id="inner-red">
        <div id="inner-red-words" class="round-corners">
          Drop Nopes Here
        </div>
        <div id="inner-red-cards">
          
        </div>
      </div>
		</div>
	</div>
	
</div>