config/routes.rb
YellowRed::Application.routes.draw do

  root :to => 'static_pages#home'
  get 'lobby', :to => 'sessions#lobby'
  get 'signup', :to => 'users#new'
  
  resource :session, :only => [:create, :destroy]
  
  resources :users, :only => [:create]
  resource :profile, :only => [:show, :edit, :update]
  
  resource :saved_search, :only => [:show, :update]
  get 'saved_search/results', :to => 'saved_searches#results'
  
  resources :messages, :only => [:index, :show, :create, :destroy]
  
  resources :maybes, :only => [:create, :update]
  delete 'maybes/:profile_id' => 'maybes#destroy'
  get 'my-maybe-list', :to => 'maybes#maybe_list'
  get 'my-nope-list', :to => 'maybes#nope_list'
  
  resources :stars, :only => [:index, :create]
  delete 'stars/:profile_id' => 'stars#destroy'
  get 'who-i-starred', :to => 'stars#index'
  get 'who-starred-me', :to => 'stars#starred_me'
  
  resources :profiles, :only => [:index, :show]
  get 'check-username/:username', :to => 'profiles#taken'
  get 'dev', :to => 'profiles#clausti'
  get ':username', :to => 'profiles#show'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :user_id,
                  :username,
                  :gender, 
                  :about_me,
                  :friends_wanted, #boolean
                  :dating_wanted, #boolean
                  :hookups_wanted, #boolean
                  :men_wanted, #boolean
                  :women_wanted, #boolean
                  :nonbinary_wanted, #boolean
                  :height, #integer in inches
                  :body_type,
                  :religion,
                  :education,
                  :children,
                  :pets,
                  :profile_photo
                  
                  has_attached_file :profile_photo, 
                                    :styles => { :full => "400x400>",
                                                :thumb => "80x80#" },
                                    :default_url => "/images/cat_:style.png" 
                  
  GENDERS          = %w( male female genderqueer nonbinary )
  HEIGHTS          = (58..84).to_a
  BODY_TYPES       = %w( skinny lean average pregnant athletic soft chubby heavy)
  RELIGIONS        = %w( none Jehovah Yaweh Allah Buddhist Hindu FSM other )
  EDUCATION_LEVELS = %w( some\ high\ school high\ school college masters PhD MD )
  CHILDREN_CHOICES = %w( have\ kids have\ kids\ &\ want\ more want\ kids don't\ want\ kids )
  PET_CHOICES      = %w( cats dogs ball\ pythons bearded\ dragons fish other )
  
  LISTS = %w( gender height body_type religion education children pets )
  
  before_save :nilify_blanks, :strip_about_me
  
  validates :user_id, 
            :presence   => true, 
            :uniqueness => true
            
  validates :username, 
            :on         => :update,
            :presence   => true, 
            :uniqueness => { :case_sensitive => false }          
            
  validates :gender, 
            :on          => :update,
            :on          => :update,
            :inclusion   => GENDERS,
            :allow_blank => true
            
  validates :height,
            :on          => :update,
            :inclusion   => HEIGHTS,
            :allow_blank => true
            
  validates :body_type,
            :on          => :update,  
            :inclusion   => BODY_TYPES,
            :allow_blank => true
            
  validates :religion,
            :on          => :update,
            :inclusion   => RELIGIONS,
            :allow_blank => true
            
  validates :education,
            :on          => :update,  
            :inclusion   => EDUCATION_LEVELS,
            :allow_blank => true
            
  validates :children,
            :on          => :update,  
            :inclusion   => CHILDREN_CHOICES,
            :allow_blank => true
            
  validates :pets,
            :on          => :update,  
            :inclusion   => PET_CHOICES,
            :allow_blank => true
                
                  
  belongs_to :user, :inverse_of => :profile
  
  has_many :maybes, :inverse_of => :profile, 
                    :dependent  => :delete_all
                    
  has_many :stars,  :inverse_of => :profile, 
                    :dependent  => :delete_all
  
  has_many :starring_users, 
           :through => :stars, 
           :source  => :user
           
  has_many :starring_profiles, 
           :through => :starring_users,
           :source  => :profile
           
  def self.height_string(height_inches)
    hieght_feet_inches = height_inches.divmod(12)
    "#{hieght_feet_inches[0]}' #{hieght_feet_inches[1]}\""
  end
  
  def photo_url
    self.profile_photo.url(:full)
  end
  
  def photo_thumb_url
    self.profile_photo.url(:thumb)
  end
  
  def height_string
    unless self.height.nil?
      Profile.height_string(self.height)
    else
      nil
    end
  end
  
  def looking_for
    looking = []
    looking << "Friends" if self.friends_wanted
    looking << "Dates" if self.dating_wanted
    looking << "Hookups" if self.hookups_wanted
    looking.join(", ")
  end
  
  def interested_in
    interested = []
    interested << "Men" if self.men_wanted
    interested << "Women" if self.women_wanted
    interested << "Genderqueer or Nonbinary folks" if self.nonbinary_wanted
    interested.join(", ")
  end
           
  private
    def nilify_blanks
      Profile::LISTS.each do |list_name|
        self[list_name] = self[list_name].blank? ? nil : self[list_name]
      end
    end
  
    def strip_about_me
      self.about_me.strip! if self.about_me
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_filter :must_be_logged_in, :only => [:taken, :clausti]
  
  def index
    @profiles = Profile.includes(:stars, :maybes)
    @profiles -= [current_user.profile]
    
    Profile.transaction do
      render :index
    end
  end
  
  def show
    if params[:username]
      @profile = Profile.find_by_username(params[:username])
      if @profile 
        render :show, :status => 200
      else
        render :json => false, :status => 422
      end
    else
      @profile = current_user.profile
      render :show, :status => 200
    end
  end
  
  def taken
    @profile = Profile.find_by_username(params[:username])
    if @profile 
      render :json => true, :status => 200
    else
      render :json => false, :status => 422
    end
  end
  
  def edit
    @profile = current_user.profile
    render :edit
  end
  
  def update
    @profile = current_user.profile
    profile_params = profile_booleans_false.merge(params[:profile])

    if @profile.update_attributes(profile_params)
      redirect_to root_url
    else
      flash.now[:errors] = @profile.errors.full_messages
      render :edit
    end
  end
  
  def clausti
    @profile = Profile.find_by_username("clausti")
    render :clausti
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/clausti.html.erb
<div id="all-content">
	
	<div id="dummy-left-sidebar" class="round-corners shadow">
		<a href="/" id="go-play-with-it">go<br>play<br>with<br>it</a>
	</div>
	<div id="central-content">
    <h3>Christina Austin</h3>
    <input type="hidden" value="clausti" id="profile-username">
    
    <div style="padding-top:10px;float:right">
      <a href='#/new-message' 
         id='new-message' 
         class='button new-message-button'
         data-id="clausti">Send a Message</a>
    </div>
                            
    <div id="profile-detail-card" class="round-corners shadow">
  
      <img src="<%= @profile.photo_url %>" 
           style="align:right" 
           class="profile-photo"
           data-id="<%= @profile.id%>">
       
    	<strong>Gender:</strong> <%= @profile.gender%><br>
    	<strong>Height:</strong> <%= @profile.height_string%><br>
      <strong>Body Type:</strong> <%= @profile.body_type%><br>
      <strong>Religion:</strong> <%= @profile.religion%><br>
      <strong>Education:</strong>
      <%= @profile.education%><br>
      <strong>Children:</strong>
      <%= @profile.children%><br>
      <strong>Pets:</strong>
      <%= @profile.pets%><br>
      <br>
      <strong>Looking For:</strong><br>
      "Interesting problems and ways to solve them"<br>
      <br>
      <strong>Interested In:</strong><br>
      "How the data models are laid out. The way the user interacts with the system, the system with itself, and the developers with the code. The pleasure acquired from things that work well."
      <br>
  
      <br>
    	<strong>About Me: </strong>
      <br>
      <%= @profile.about_me%><br>
    
    </div>
  </div>
	<div id="right-sidebar">
		<div id="yellow-box" class="round-corners shadow">
		</div>
		
		<div id="red-box" class="round-corners shadow">
		</div>
	</div>
	
</div>

app/views/profiles/edit.html.erb
<div id="all-content">
	
	<div id="dummy-left-sidebar" class="round-corners shadow">
		<a href="/#/profile" id="back-to-me"><sub>&hearts;</sub>me</a>
	</div>
	
	<div id="profile-edit-card" class="round-corners shadow">
		<%= render "shared/errors_marquee" %>
	
		<form action="<%= profile_url %>" method="post"          id="profile-edit-form"
                                      accept-charset="utf-8" enctype="multipart/form-data">
			<input type="hidden" name="_method" value="PUT">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		
		<div id="username">
			<label for="profile_username">Username</label>
			<input type="text" name="profile[username]" value="<%= @profile.username %>" id="profile_username">
		</div>
		<div id="gender">
			<label for="profile_gender">Gender</label>
			<select name="profile[gender]" id="profile_gender">
				<option value=""></option>
				<% options = Profile::GENDERS %>
				<% options.each do |gender| %>
			    <option value="<%= gender %>"
						<% if @profile.gender == gender %>
								selected
						<% end %>><%= gender %></option>
				<% end %>				
			</select><br>
		</div>
	
		<div id="profile-form-seeking">
			<div class="checkbox-group">
				Looking for:<br>
					<div class="checkbox-group">
						<input type="checkbox" 
									 name="profile[friends_wanted]" 
									 value="true"
									 <% if @profile.friends_wanted %>
										 checked
									 <% end %>>Friends<br>
						<input type="checkbox" 
									 name="profile[dating_wanted]" 
									 value="true"
									 <% if @profile.dating_wanted %>
										 checked
									 <% end %>>Dating<br>
						<input type="checkbox" 
									 name="profile[hookups_wanted]" 
									 value="true"
									 <% if @profile.hookups_wanted %>
										 checked
									 <% end %>>Hookups<br>
					</div>
			</div>
	
			<div class="checkbox-group">
				Interested in:<br>
					<div class="checkbox-group">
						<input type="checkbox" 
									 name="profile[men_wanted]" 
									 value="true"
									 <% if @profile.men_wanted %>
										 checked
									 <% end %>>Men<br>
						<input type="checkbox" 
									 name="profile[women_wanted]" 
									 value="true"
									 <% if @profile.women_wanted %>
										 checked
									 <% end %>>Women<br>
						<input type="checkbox" 
									 name="profile[nonbinary_wanted]" 
									 value="true"
									 <% if @profile.nonbinary_wanted %>
										 checked
									 <% end %>>Genderqueer/Nonbinary folks<br>	
					</div>
			</div>
		
		</div>

		<div id="about-me">
			<label for="profile_about_me">About me:</label><br>
			<textarea name="profile[about_me]" 
								id="profile_about_me" 
								rows="10" 
								cols="41"><%= @profile.about_me %></textarea>
      <br>
      <div class="profile-thumb-photo" 
           style="margin-left:5px;margin-right:15px"
           align="bottom-left">
        <%= image_tag @profile.profile_photo.url(:thumb) %>
      </div> 
      Profile photo:
      <input type="file" name="profile[profile_photo]"  id="profile_profile_photo">
      <br>
                  
		</div>
	
		<div id="my-stats">
			My Stats:<br>
			<label for="profile_height">Height</label>
			<select name="profile[height]" id="profile_height">
				<option value=""></option>
				<% options = Profile::HEIGHTS %>
				<% options.each do |height| %>
				<% hieght_feet_inches = height.divmod(12) %>
			    <option value="<%= height %> %>"
						<% if @profile.height == height %>
								selected
						<% end %>><%=hieght_feet_inches[0]%>' <%=hieght_feet_inches[1]%>"</option>
				<% end %>	
			</select><br>		
		
			<label for="profile_body_type">Body Type</label>
			<select name="profile[body_type]" id="profile_body_type">
				<option value=""></option>
				<% options = Profile::BODY_TYPES %>
				<% options.each do |body_type| %>
			    <option value="<%= body_type %>"
						<% if @profile.body_type == body_type %>
							selected
					  <% end %>><%= body_type %></option>
				<% end %>				
			</select><br>

			<label for="profile_religion">Religion</label>
			<select name="profile[religion]" id="profile_religion">
				<option value=""></option>
				<% options = Profile::RELIGIONS %>
				<% options.each do |religion| %>
			    <option value="<%= religion %>"
						<% if @profile.religion == religion %>
							selected
					  <% end %>><%= religion %></option>
				<% end %>				
			</select><br>
		
			<label for="profile_education">Education</label>
			<select name="profile[education]" id="profile_education">
				<option value=""></option>
				<% options = Profile::EDUCATION_LEVELS %>
				<% options.each do |education| %>
			    <option value="<%= education %>"
						<% if @profile.education == education %>
							selected
					  <% end %>><%= education %></option>
				<% end %>					
			</select><br>
		
			<label for="profile_children">Kids?</label>
			<select name="profile[children]" id="profile_children">
				<option value=""></option>
				<% options = Profile::CHILDREN_CHOICES %>
				<% options.each do |children| %>
			    <option value="<%= children %>"
						<% if @profile.children == children %>
							selected
					  <% end %>><%= children %></option>
				<% end %>				
			</select><br>
		
			<label for="profile_pets">Pets?</label>
			<select name="profile[pets]" id="profile_pets">
				<option value=""></option>
				<% options = Profile::PET_CHOICES %>
				<% options.each do |pets| %>
			    <option value="<%= pets %>"
						<% if @profile.pets == pets %>
							selected
					  <% end %>><%= pets %></option>
				<% end %>				
			</select><br>
		</div>
			<div style="position:relative;top:390px;left:-111px;padding:5px">
				<input class="button" type="submit" value="Save Profile">
			</div>
		</form>
		<br>
		<div style="position:relative;top:90px;left:35px;padding:5px">
			<%= button_to "Go to Home without saving", root_url, :method => :get, :class => "button" %>
		</div>
	</div>
	
	<div id="right-sidebar">
		<div id="yellow-box" class="round-corners shadow">
		</div>
		
		<div id="red-box" class="round-corners shadow">
		</div>
	</div>
	
</div>