config/routes.rb
YellowRed::Application.routes.draw do

  root :to => 'static_pages#home'
  get 'lobby', :to => 'sessions#lobby'
  get 'signup', :to => 'users#new'
  
  resource :session, :only => [:create, :destroy]
  
  resources :users, :only => [:create]
  resource :profile, :only => [:show, :edit, :update]
  
  resource :saved_search, :only => [:show, :update]
  get 'saved_search/results', :to => 'saved_searches#results'
  
  resources :messages, :only => [:index, :show, :create, :destroy]
  
  resources :maybes, :only => [:create, :update]
  delete 'maybes/:profile_id' => 'maybes#destroy'
  get 'my-maybe-list', :to => 'maybes#maybe_list'
  get 'my-nope-list', :to => 'maybes#nope_list'
  
  resources :stars, :only => [:index, :create]
  delete 'stars/:profile_id' => 'stars#destroy'
  get 'who-i-starred', :to => 'stars#index'
  get 'who-starred-me', :to => 'stars#starred_me'
  
  resources :profiles, :only => [:index, :show]
  get 'check-username/:username', :to => 'profiles#taken'
  get 'dev', :to => 'profiles#clausti'
  get ':username', :to => 'profiles#show'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token
  
  before_validation(:on => :create) do
    self.reset_session_token
  end
  
  validates :email, :password_digest, :session_token, :presence => true
  validates :email, :uniqueness => {:case_sensitive => false}
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  
  has_one :profile, :inverse_of => :user, :dependent => :delete
  has_one :saved_search, :inverse_of => :user, :dependent => :delete
  
  has_many :messages_sent, 
           :class_name => "Message",
           :foreign_key => :sender_id,
           :inverse_of => :sender,
           :dependent => :delete_all
           
  has_many :messages_recd, 
           :class_name => "Message",
           :foreign_key => :recipient_id,
           :inverse_of => :recipient,
           :dependent => :delete_all
           
  has_many :maybes, :inverse_of => :user, :dependent => :delete_all
  
  has_many :all_maybe_profiles,
           :through => :maybes,
           :source => :profile
  
  has_many :stars, :inverse_of => :user, :dependent => :delete_all

  has_many :starred_profiles,
           :through => :stars,
           :source => :profile
                      
  has_many :starring_profiles, 
           :through => :profile,
           :source => :starring_profiles
           
  
  def self.find_by_credentials(user_hash)
    @user = User.find_by_email(user_hash[:email])
    
    if @user && @user.has_password?(user_hash[:password])
      @user
    else
      nil
    end
  end
  
  def self.find_by_username(username)
    Profile.find_by_username(username).user
  end
  
  def password=(raw_pw) 
    @password = raw_pw
    self.password_digest = BCrypt::Password.create(raw_pw)
  end
  
  def password
    @password
  end
  
  def has_password?(tent_pw)
    BCrypt::Password.new(self.password_digest) == tent_pw
  end
  
  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64(16)
  end
  
  def messages
    self.messages_sent + self.messages_recd
  end
  
  def maybe_profiles
    self.all_maybe_profiles.where("prefer = true")
  end
  
  def nope_profiles
    self.all_maybe_profiles.where("prefer = false")
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :must_be_logged_in, :only => [:new, :create]
  
  def new
    @user = User.new
    @profile = Profile.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @user.profile = Profile.create(:username => params[:username])
    @user.saved_search = SavedSearch.new
    
    if @user.save
      login_user!
      redirect_to edit_profile_url
    else
      @profile = Profile.new(:username => params[:username])
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div id="all-content">
	<div id="lobby-sidebar" class="round-corners shadow">

		<%= render "shared/errors_marquee" %>

		<form action="<%= users_url %>" method="post" accept-charset="utf-8">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      
  			<label for="user_username">Username</label><br>
  			<input type="text" name="username" value="<%= @profile.username %>" id="user_username">
        <br>
        
				<label for="user_email">Email</label><br>
				<input type="text" name="user[email]" value="<%= @user.email %>" id="user_email">
				<br>

				<label for="user_password">Password</label><br>
				<input type="password" name="user[password]" id="user_password">
																							
				<input type="submit" value="Sign Up!" class="button" style="display:inline">
	
		</form>

		<%= button_to "Back to Lobby", lobby_url, :method => :get, 
																							:class => "button" %>

	</div>
	
	<%= render "shared/lobby_blurb" %>

</div>