config/routes.rb
YellowRed::Application.routes.draw do

  root :to => 'static_pages#home'
  get 'lobby', :to => 'sessions#lobby'
  get 'signup', :to => 'users#new'
  
  resource :session, :only => [:create, :destroy]
  
  resources :users, :only => [:create]
  resource :profile, :only => [:show, :edit, :update]
  
  resource :saved_search, :only => [:show, :update]
  get 'saved_search/results', :to => 'saved_searches#results'
  
  resources :messages, :only => [:index, :show, :create, :destroy]
  
  resources :maybes, :only => [:create, :update]
  delete 'maybes/:profile_id' => 'maybes#destroy'
  get 'my-maybe-list', :to => 'maybes#maybe_list'
  get 'my-nope-list', :to => 'maybes#nope_list'
  
  resources :stars, :only => [:index, :create]
  delete 'stars/:profile_id' => 'stars#destroy'
  get 'who-i-starred', :to => 'stars#index'
  get 'who-starred-me', :to => 'stars#starred_me'
  
  resources :profiles, :only => [:index, :show]
  get 'check-username/:username', :to => 'profiles#taken'
  get 'dev', :to => 'profiles#clausti'
  get ':username', :to => 'profiles#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YellowRed.me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="site-header">
		<div id="logo-home-link">
			<a href="/"><span style="color:#FCE700">Yellow</span><span 
									      style="color:#FF0000">red</span><span 
									      style="color:#068A19"><span 
									      style="font-size:14pt"><sub>&hearts;</sub></span>me</span></a>          
      <span id="site-tagline">
        a dating site
      </span>
		</div>
  

		<% unless current_user.nil? %>
			<div id="current-user-thumbnail-utility" class="round-corners shadow">
					Welcome, <%= current_user.profile.username %>!
					<%= button_to "Log Out", session_url, :method => :delete, :class => "button" %>
			</div>
		<% end %>
	</div>
	
<%= yield %>

</body>
</html>